---
name: build and push docker image

on:
  workflow_call:
    inputs:
      runner:
        description: "github actions runner"
        required: true
        type: string
      image_name:
        description: "image name - default to repo name"
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      tags:
        description: "tags for image"
        required: true
        type: string

    outputs:
      metadata:
        description: "docker metadata"
        value: ${{ jobs.docker-build-push.outputs.metadata }}

jobs:
  docker-build-push:
    runs-on:
      - self-hosted
      - ${{ inputs.runner }}
    permissions:
      contents: read

    outputs:
      metadata: ${{ steps.meta.outputs.json }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v3.5.0

      # https://github.com/marketplace/actions/cosign-installer
      - name: setup cosign
        uses: sigstore/cosign-installer@v3.0.2
        with:
          cosign-release: v1.13.1

      # Workaround: https://github.com/docker/build-push-action/issues/461
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver: docker

      # https://github.com/marketplace/actions/docker-metadata-action
      - name: extract metadata for docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ inputs.image_name }}
          tags: ${{ inputs.tags }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: build and push docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
