---
name: create release in github

on:
  workflow_call:
    inputs:
      runner:
        description: '["some-runners"]'
        required: true
        type: string

    secrets:
      github-app-id:
        description: "github app id"
        required: false
      github-app-key:
        description: "github app private key"
        required: false

jobs:
  create-release:
    name: release
    runs-on: ${{fromJSON(inputs.runner)}}
    permissions:
      contents: write

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v4.1.1

      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@v1.10.3
        with:
          app-id: ${{ secrets.github-app-id }}
          private-key: ${{ secrets.github-app-key }}

      # https://github.com/marketplace/actions/gh-release
      - name: create release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # v2.0.9
        with:
          token: ${{ steps.generate-token.outputs.token }}
