---
name: tag image in github

on:
  workflow_call:
    inputs:
      runner:
        description: '["self-hosted", "some-runner"]'
        required: true
        type: string
      registry:
        description: "registry url"
        required: false
        type: string
        default: "ghcr.io"
      subpath:
        description: "subpath if needed, f.e. app-name"
        required: false
        type: string
      tags:
        description: "tags for image - default sha"
        required: false
        type: string
        default: ${{ github.sha }}

jobs:
  tag-image-github:
    name: github
    runs-on: ${{fromJSON(inputs.runner)}}
    permissions:
      contents: read
      id-token: write
      packages: write
    env:
      image-path: ${{ github.repository }}/${{ inputs.subpath }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v3.5.0

      # https://github.com/marketplace/actions/docker-login
      - name: log into registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/docker-registry-tag
      - name: tag image
        uses: shrink/actions-docker-registry-tag@v3.0.0
        with:
          registry: ${{ inputs.registry }}
          repository: ${{ env.image-path }}
          target: ${{ github.sha }}
          tags: ${{ inputs.tags }}
