---
name: tag image in google

on:
  workflow_call:
    inputs:
      runner:
        description: '["some-runners"]'
        required: true
        type: string
      workload-identity-provider:
        description: "projects/<number>/locations/global/..."
        required: true
        type: string
      service-account:
        description: "github-artifactregistry@..."
        required: true
        type: string
      registry:
        description: "registry url"
        required: true
        type: string
      gcp:
        description: "google cloud project id"
        required: true
        type: string
      repository:
        description: "repository"
        required: true
        type: string
      source-path:
        description: "path to source image"
        required: true
        type: string
      target-path:
        description: "path to target image"
        required: true
        type: string

jobs:
  tag-image-google:
    name: google
    runs-on: ${{fromJSON(inputs.runner)}}
    permissions:
      contents: read
      id-token: write
    env:
      base-path: ${{ inputs.registry }}/${{ inputs.gcp }}/${{ inputs.repository }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/authenticate-to-google-cloud
      - name: authenticate to google cloud
        id: auth
        uses: "google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935" # v2.1.8
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}

      # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4
        with:
          # Workload Identity Federation requires version 363.0.0 or newer.
          version: ">= 363.0.0"

      - name: retag image
        run: |
          gcloud container images add-tag \
            ${{ env.base-path }}/${{ inputs.source-path }}:${{ github.sha }} \
            ${{ env.base-path }}/${{ inputs.target-path }}:${{ github.ref_name }}
