---
name: tag image in github

on:
  workflow_call:
    inputs:
      runner:
        description: '["some-runners"]'
        required: true
        type: string
      registry:
        description: "registry url"
        required: false
        type: string
        default: "ghcr.io"
      repository:
        description: "repository"
        required: true
        type: string
      source-path:
        description: "path to source image"
        required: true
        type: string
      target-path:
        description: "path to target image"
        required: true
        type: string

jobs:
  tag-image-github:
    name: github
    runs-on: ${{fromJSON(inputs.runner)}}
    permissions:
      contents: read
      id-token: write
      packages: write
    env:
      base-path: ${{ inputs.registry }}/${{ inputs.repository }}

    steps:
      # https://github.com/marketplace/actions/docker-login
      - name: log into registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: retag image
        run: |
          docker pull ${{ env.base-path }}/${{ inputs.source-path }}:${{ github.sha }}
          docker tag ${{ env.base-path }}/${{ inputs.source-path }}:${{ github.sha }} ${{ env.base-path }}/${{ inputs.target-path }}:${{ github.ref_name }}
          docker push ${{ env.base-path }}/${{ inputs.target-path }}:${{ github.ref_name }}
