---
name: tag image in google

on:
  workflow_call:
    inputs:
      runner:
        description: '["self-hosted", "some-runner"]'
        required: true
        type: string
      workload-identity-provider:
        description: "projects/<number>/locations/global/..."
        required: true
        type: string
      service-account:
        description: "github-artifactregistry@..."
        required: true
        type: string
      registry:
        description: "registry url"
        required: true
        type: string
      gcp:
        description: "google cloud project id"
        required: true
        type: string
      repository:
        description: "repository"
        required: true
        type: string
      source-path:
        description: "path to source image"
        required: true
        type: string
      target-path:
        description: "path to target image"
        required: true
        type: string

jobs:
  tag-image-google:
    name: google
    runs-on: ${{fromJSON(inputs.runner)}}
    permissions:
      contents: read
      id-token: write
    env:
      base-path: ${{ inputs.registry }}/${{ inputs.gcp }}/${{ inputs.repository }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v3.5.0

      # https://github.com/marketplace/actions/authenticate-to-google-cloud
      - name: authenticate to google cloud
        id: auth
        uses: "google-github-actions/auth@v1.0.0"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}

      # https://github.com/marketplace/actions/docker-login
      - name: log into registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: retag image
        run: |
          docker pull ${{ env.base-path }}/${{ inputs.source-path }}:${{ github.sha }}
          docker tag ${{ env.base-path }}/${{ inputs.source-path }}:${{ github.sha }} ${{ env.base-path }}/${{ inputs.target-path }}:${{ github.ref_name }}
          docker push ${{ env.base-path }}/${{ inputs.target-path }}:${{ github.ref_name }}
