---
name: tag image in google

on:
  workflow_call:
    inputs:
      runner:
        description: '["self-hosted", "some-runner"]'
        required: true
        type: string
      workload-identity-provider:
        description: "projects/<number>/locations/global/..."
        required: true
        type: string
      service-account:
        description: "github-artifactregistry@..."
        required: true
        type: string
      registry:
        description: "registry url"
        required: true
        type: string
      gcp:
        description: "google cloud project id"
        required: true
        type: string
      repository:
        description: "repository"
        required: true
        type: string
      subpath:
        description: "subpath to image, f.e. integration/app-name"
        required: true
        type: string
      tags:
        description: "tags for image - default sha"
        required: false
        type: string
        default: ${{ github.sha }}

jobs:
  tag-image-google:
    name: google
    runs-on: ${{fromJSON(inputs.runner)}}
    permissions:
      contents: read
      id-token: write
    env:
      image-path: ${{ inputs.gcp }}/${{ inputs.repository }}/${{ inputs.subpath }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@v3.5.0

      # https://github.com/marketplace/actions/authenticate-to-google-cloud
      - name: authenticate to google cloud
        id: auth
        uses: "google-github-actions/auth@v1.0.0"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}

      # https://github.com/marketplace/actions/docker-login
      - name: log into registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # https://github.com/marketplace/actions/docker-registry-tag
      - name: tag image
        uses: shrink/actions-docker-registry-tag@v3.0.0
        with:
          registry: ${{ inputs.registry }}
          repository: ${{ env.image-path }}
          target: ${{ github.sha }}
          tags: ${{ inputs.tags }}
